name: sim
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - backcall=0.2.0=py_0
  - blas=1.0=openblas
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - freetype=2.10.3=ha233b18_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.2=py37_0
  - kiwisolver=1.2.0=py37ha1cc60f_0
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.2.1=h0a44026_1007
  - libgfortran=3.0.1=h93005f0_2
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=h0794777_0
  - libpng=1.6.37=hb0a8c7a_2
  - llvm-openmp=11.0.0=h73239a0_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h11da6c2_0
  - ncurses=6.2=h0a44026_1
  - numpy=1.19.2=py37h1efc2f6_1
  - openssl=1.1.1h=haf1e3a3_0
  - pandas=1.1.3=py37hb1e8313_0
  - parso=0.7.0=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.2.3=py37_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.7.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.7.6=h359304d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - readline=7.0=h1de35cc_5
  - scipy=1.5.2=py37hadf427e_0
  - seaborn=0.11.0=py_0
  - setuptools=50.3.0=py37h0dc7051_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.0.4=py37h60d8a13_2
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - pyqt5==5.15.1
    - pyqt5-sip==12.8.1
prefix: /opt/miniconda3/envs/sim
